# -*- mode: python ; coding: utf-8 -*-
# One-folder CardLift GUI bundle. Version resource is generated by
# packaging/generate_version_info.py (run by packaging/build_release.ps1
# before this spec builds) so it always matches deckforge.__version__.
# No installer/signing yet.

import os

SPEC_DIR = os.path.dirname(os.path.abspath(SPEC))
VERSION_INFO_PATH = os.path.join(SPEC_DIR, 'packaging', 'version_info.txt')

a = Analysis(
    ['gui_app.py'],
    pathex=['src'],
    binaries=[],
    datas=[('sample_decks/CardLift_Demo_Deck.pdf', 'sample_decks')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CardLift',
    debug=False,
    strip=False,
    upx=False,
    console=False,
    version=VERSION_INFO_PATH if os.path.exists(VERSION_INFO_PATH) else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='CardLift',
)
