"""Generate the PyInstaller Windows version-info file from deckforge.__version__.

Run before building deckforge_gui.spec so the packaged .exe's file
properties (Details tab in Windows Explorer) always match the version
string the GUI itself displays, instead of drifting out of sync with a
hand-maintained copy. Output: packaging/version_info.txt (not committed;
regenerated on every build).
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from deckforge import __version__ as VERSION  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent / "version_info.txt"

COMPANY_NAME = "RPG Frequencies"
PRODUCT_NAME = "CardLift"
FILE_DESCRIPTION = "CardLift - Print-and-Play Card Extractor"
LEGAL_COPYRIGHT = "Copyright (C) 2026 Allen Dodge. Licensed under AGPLv3."
ORIGINAL_FILENAME = "CardLift.exe"

TEMPLATE = """\
# UTF-8
#
# Auto-generated by packaging/generate_version_info.py from
# deckforge.__version__ ({version}). Do not edit by hand -- edit
# src/deckforge/__init__.py and regenerate instead.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company_name}'),
        StringStruct('FileDescription', '{file_description}'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', '{product_name}'),
        StringStruct('LegalCopyright', '{legal_copyright}'),
        StringStruct('OriginalFilename', '{original_filename}'),
        StringStruct('ProductName', '{product_name}'),
        StringStruct('ProductVersion', '{version}')])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def numeric_filevers(version: str) -> tuple[int, int, int, int]:
    """Extract a four-part numeric tuple Windows requires (e.g. (0, 1, 0, 0))."""
    match = re.match(r"^(\d+)\.(\d+)\.(\d+)", version)
    if not match:
        raise ValueError(f"Cannot parse a numeric version from {version!r}")
    major, minor, patch = (int(part) for part in match.groups())
    return (major, minor, patch, 0)


def main() -> None:
    content = TEMPLATE.format(
        version=VERSION,
        filevers=numeric_filevers(VERSION),
        company_name=COMPANY_NAME,
        file_description=FILE_DESCRIPTION,
        product_name=PRODUCT_NAME,
        legal_copyright=LEGAL_COPYRIGHT,
        original_filename=ORIGINAL_FILENAME,
    )
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} for version {VERSION}")


if __name__ == "__main__":
    main()
